### ISSUE TITLE
105$: [nvim-lspconfig] Only lint on insert with quick-lint

### ISSUE THREAD

**Issue by vegerot** [quick-lint/quick-lint-js#909] opened 2023-01-16 00:56 UTC
The vim docs for quick-lint say that I can lint while in insert mode.  However, while quick-lint is quick, most of my other linters are not quick.  Is there a way to lint in insert mode for _only_ quick-lint?  The docs only describe how to do it for _all_ linters:

```lua
    vim.lsp.handlers['textDocument/publishDiagnostics'] = vim.lsp.with(
      vim.lsp.diagnostic.on_publish_diagnostics, {
        update_in_insert = true,
      }
    )
```

**Comment by strager** [comment] 2023-01-16 08:59
Great idea!

**Comment by vegerot** [comment] 2023-04-22 20:09
please add an extra $100 to this issue (from me)

**Comment by vegerot** [comment] 2023-04-22 20:18
https://vi.stackexchange.com/questions/41975/enable-update-in-insert-only-for-certain-extensions

**Comment by vegerot** [comment] 2023-04-22 21:34
off-topic: I found a shorter version of this by reading the neovim help pages


```lua
vim.diagnostic.config({
	update_in_insert = true,
})
```

**Comment by strager** [comment] 2023-04-26 21:54
>  Could we make a `quick-lint` namespace?

I suspect that a namespace is for plugins like nvim-lspconfig, not for plugins (LSP servers) like quick-lint-js. But perhaps nvim-lspconfig creates one namespace for each registered LSP server?

**Comment by RossBarnie** [comment] 2023-09-08 09:27
@strager I claim this for-hire task. I expect payment after I complete this task. I will email the quick-lint-js team if I am assigned this task.

**Comment by strager** [comment] 2023-09-08 09:34
@RossBarnie The title has a mistake because the reporter is an asshole. The dollar amount was intended to be 5$, not 105$.

I think 15$ is more appropriate. Do you agree to 15$?

**Comment by RossBarnie** [comment] 2023-09-08 09:42
Yes I agree to $15.

**Comment by vegerot** [comment] 2023-09-08 16:25
I also intend on adding $100$.  We'll talk payment methods after it's completed.  You like Walmart gift cards?

**Closed** 2023-09-18 23:40 UTC
Labels: for hire

**Comment by vegerot** [comment] 2023-09-19 06:40
I'll try this out tomorrow and send the money :)

**Comment by vegerot** [comment] 2024-09-01 04:08
@RossBarnie it works!  But you don't have Sponsors enabled :(
