### ISSUE TITLE
12$: Neovim: native LSP plugin

### ISSUE THREAD

**Issue by strager** [quick-lint/quick-lint-js#105] opened 2020-12-25 10:40 UTC

**Comment by tiagovla** [comment] 2021-05-07 03:20
I claim this for-hire task. I expect payment after I complete this task. I will email the quick-lint-js team if I am assigned this task.

**Comment by tiagovla** [comment] 2021-05-11 03:07
Neovim has its own official LSP configuration [plugin](https://github.com/neovim/nvim-lspconfig/), so every server does not need an individual plugin.
I submitted a configuration for quick-lint-js [there](https://github.com/neovim/nvim-lspconfig/pull/887). Until it get accepted or if it doesn't, it can be used with the following configuration:
```lua
-- init.lua
local lspconfig = require("lspconfig")
local configs = require("lspconfig/configs")

if not lspconfig.quick_lint_js then
    configs.quick_lint_js = {
        default_config = {
            cmd = {"quick-lint-js", "--lsp-server"},
            filetypes = {"javascript"},
            root_dir = function(fname)
                return lspconfig.util.find_node_modules_ancestor(fname) or
                           lspconfig.util.find_git_ancestor(fname) or
                           vim.loop.os_homedir()
            end,
            settings = {},
        },
    }
end
lspconfig.quick_lint_js.setup {}
```
If it does get accepted, it can be configured like this:
```lua
require("lspconfig").quick_lint_js.setup {}
```

####  Additional configuration to reproduce the problem I was having with autocomplete, which is a third party plugin:

[Packer](https://github.com/wbthomason/packer.nvim) configuration:
```lua
vim.lsp.set_log_level("debug")
require("packer").startup(function()
    use "wbthomason/packer.nvim"
    use "neovim/nvim-lspconfig" -- install lspconfig
    use "hrsh7th/nvim-compe" -- install autocomplete plugin
end)
-- :PackerInstall :PackerCompile
```

[Compe](https://github.com/hrsh7th/nvim-compe/) configuration:
```lua
require("compe").setup {
    enabled = true,
    autocomplete = true,
    debug = false,
    min_length = 1,
    preselect = "enable",
    throttle_time = 80,
    source_timeout = 200,
    incomplete_delay = 400,
    max_abbr_width = 100,
    max_kind_width = 100,
    max_menu_width = 100,
    documentation = true,

    source = {
        nvim_lsp = true,
    },
}
```

Logs:
```sh
[ DEBUG ] 2021-05-10T21:58:11-0300 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:390 ]	"rpc.send.payload"	{  id = 2,  jsonrpc = "2.0",  method = "textDocument/completion",  params = {    context = {      triggerKind = 1    },    position = {      character = 1,      line = 0    },    textDocument = {      uri = "file:///home/tiagovla/.config/nvim/hello.js"    }  }}
[ ERROR ] 2021-05-10T21:58:11-0300 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"/home/tiagovla/.local/share/nvim/servers/quick-lint-js/node_modules/.bin/quick-lint-js"	"stderr"	"/__w/quick-lint-js/quick-lint-js/src/lsp-server.cpp:59: internal check failed in handle_request: false\n"

```
### What I found:

* Quick-lint-js does not implement ``textDocument/completion`` yet and it also [does not say it does](https://github.com/quick-lint/quick-lint-js/blob/master/src/lsp-server.cpp#L98:L100) in the initialize request handler.

* ``:lua print(vim.inspect(vim.lsp.get_active_clients()))`` does not show any completion provider, only the ``textDocumentSync`` defined in the initialize request handler. Neovim is aware it doesn't have it.

* The autocomplete plugin does not check if it has the completion capability, it just sends the request and the server crashes because it can't handle the ``textDocument/completion`` request. 

* **It works fine without the autocomplete plugin**.

*  It's also possible to use a general language server like [efm](https://github.com/mattn/efm-langserver) to handle the LSP and configure quick-lint-js as a linter there.

**Comment by strager** [comment] 2021-05-11 03:53
> Neovim has its own official LSP configuration [plugin](https://github.com/neovim/nvim-lspconfig/), so every server does not need an individual plugin.
> I submitted a configuration for quick-lint-js [there](https://github.com/neovim/nvim-lspconfig/pull/887).

I'd rather us maintain a local plugin and iron out its kinks before submitting a plugin to upstream Neovim for publishing.

> Until it get accepted or if it doesn't, it can be used with the following configuration:
> 
> ```lua
> -- init.lua
> local lspconfig = require("lspconfig")
> local configs = require("lspconfig/configs")
> 
> if not lspconfig.quick_lint_js then
>     configs.quick_lint_js = {
>         default_config = {
>             cmd = {"quick-lint-js", "--lsp-server"},
>             filetypes = {"javascript"},
>             root_dir = function(fname)
>                 return lspconfig.util.find_node_modules_ancestor(fname) or
>                            lspconfig.util.find_git_ancestor(fname) or
>                            vim.loop.os_homedir()
>             end,
>             settings = {},
>         },
>     }
> end
> lspconfig.quick_lint_js.setup {}
> ```

Can we ship this with quick-lint-js (e.g. with its Debian package) as an auto-loaded plugin like we have with our ALE plugin? If so, please make a pull request.

Quick review: why do we need `root_dir`? Seems like wasted effort when opening a file. Does `root_dir` cause multiple quick-lint-js servers to be created? Does it cause only one to be created?

**Comment by tiagovla** [comment] 2021-05-11 05:53
> 
> I'd rather us maintain a local plugin and iron out its kinks before submitting a plugin to upstream Neovim for publishing.
> 
If someone wants to try it without installing anything else that they don't already have, that's probably the best way. And they can easily customize the configuration using that setup function. But I can see your point. Should I close the PR there?
> 
> Can we ship this with quick-lint-js (e.g. with its Debian package) as an auto-loaded plugin like we have with our ALE plugin? If so, please make a pull request.
> 
It should work the same way.
> Quick review: why do we need `root_dir`? Seems like wasted effort when opening a file. Does `root_dir` cause multiple quick-lint-js servers to be created? Does it cause only one to be created?

It needs it to detect the base of the project. For example, if you ask the server to rename a function, it needs that to know when to stop. I believe every file inside that root_dir will be handled by the same instance of the server. At least it's how it shows with ``:LspInfo``. Some servers won't even start if that root directory cannot be found, in most cases the root is usually a directory with .git.

**Comment by strager** [comment] 2021-05-11 09:05
> If someone wants to try it without installing anything else that they don't already have, that's probably the best way.

How could someone try quick-lint-js in Neovim without also installing the quick-lint-js program (which definitely *won't* be bundled with Neovim)?

> And they can easily customize the configuration using that setup function.

If it's standard practice to have users register LSP servers, then we should follow standard practice.

> Should I close the PR there?

If you think we can get useful feedback from upstream (e.g. best practices and security), the upstream PR sounds useful.

> It needs it to detect the base of the project. For example, if you ask the server to rename a function, it needs that to know when to stop.

This isn't relevant to quick-lint-js. I can see it being relevant to LSP and other LSP servers though, so I can see why `root_dir` might be assumed or required by Neovim.

> I believe every file inside that root_dir will be handled by the same instance of the server. At least it's how it shows with `:LspInfo`. Some servers won't even start if that root directory cannot be found, in most cases the root is usually a directory with .git.

If the `root_dir` doesn't really matter to Neovim, would it make sense to choose `/` (POSIX) or `c:\` (Windows) unconditionally?

**Comment by tiagovla** [comment] 2021-05-11 20:04
>
> How could someone try quick-lint-js in Neovim without also installing the quick-lint-js program (which definitely _won't_ be bundled with Neovim)?
>

I meant to not add any other plugin to their neovim config if they choose to install it with npm, which is what I do, otherwise I just build it from source. I find it easier to update and keep them local to a single path, but I have been using vim/neovim for a few months only, so not sure how others do it.

> If the `root_dir` doesn't really matter to Neovim, would it make sense to choose `/` (POSIX) or `c:\` (Windows) unconditionally?

```
{root_dir}
    Required for some servers, optional for others.
    Function of the form `function(filename, bufnr)`.
    Called on new candidate buffers being attached-to.
    Returns either a root_dir or nil.

    If a root_dir is returned, then this file will also be attached. You
    can optionally use {filetype} to help pre-filter by filetype.

    If a root_dir is returned which is unique from any previously returned
    root_dir, a new server will be spawned with that root_dir.

    If nil is returned, the buffer is skipped.

    See |lspconfig.util.search_ancestors()| and the functions which use it:
    - |lspconfig.util.root_pattern(pattern1, pattern2...)| is a variadic function which
      takes string patterns as arguments, and finds an ancestor 
      which contains one of the files matching the pattern. 
      Each pattern can be a specific filename, such as ".git", or a glob.  
      See `:help glob` for allowed patterns.  This is equivalent to
      coc.nvim's "rootPatterns"
    - Related utilities for common tools:
      - |lspconfig.util.find_git_root()|
      - |lspconfig.util.find_node_modules_root()|
      - |lspconfig.util.find_package_json_root()|
```
I have yet not seen a single server that doesn't define it locally.

And even if it says it's optional for some servers, the ``root_dir`` is not optional, otherwise I get the error ``root_dir: expected function, got nil``.

Another case I can think of is if you have a few projects attached to the same server and you want to stop the linter in only one of those projects, it would stop it everywhere. Of course you could say, detach the buffers from that unique server instance running, but that's not how all other servers are doing it.

**Closed** 2021-10-07 00:48 UTC
Labels: for hire
