### ISSUE TITLE
feature idea: parse git merge conflicts

### ISSUE THREAD

**Issue by vegerot** [quick-lint/quick-lint-js#1156] opened 2024-01-03 23:43 UTC
Consider code like 

```js
<<<<<<< head
      const a =7;
=======
      setTimeout();
>>>>>>> 6e82b52a555 (fix(platform): asdf)
```

With this code, quick-lint gets confused and is unable to lint the rest of the file.  Instead, quick-lint could add diagnostics for

```js
<<<<<<< head 
^ // error: merge conflict marker detected
```

.  I could use my key bind for "jump to next diagnostic" to jump to merge conflicts and fix them.  More importantly, quick-lint could continue linting the rest of the file.  Of course, there would still be "issues" like

```js
<<<<<<< head
      const a =7;
=======
      const a = 8
                ^ you couldn't get enough of a, so you had to make two, huh?
>>>>>>> 6e82b52a555 (fix(platform): asdf)
```

but arguably if you're trying to resolve a conflict these sorts of diagnostics would be helpful 🙂

**Comment by vegerot** [comment] 2024-01-03 23:45
implementation idea: simply treat lines starting with `<<<<<<<`, `=======`, or `>>>>>>>` as comments.  This wouldn't call out the locations of them as diagnostics but at least it'd let quick-lint understand the whole file.

**Comment by strager** [comment] 2024-01-03 23:49
Duplicate of #404

**Closed by strager** 2024-01-03 23:49 UTC

**Comment by vegerot** [comment] 2024-01-03 23:54
> Duplicate of #404

I can't find that Issue
