### ISSUE TITLE
Arch Linux package conflicting files

### ISSUE THREAD

**Issue by cahian** [quick-lint/quick-lint-js#572] opened 2021-12-09 19:24 UTC
When I was updating the system packages I got this error: 

![2021-12-09 15-59-01](https://user-images.githubusercontent.com/55219561/145462107-cb0d32f0-cc7d-416c-adf3-182f9def24a6.png)

**Comment by strager** [comment] 2021-12-10 05:16
I was able to reproduce the issue. On my Manjaro VM, it looks like Vim Airline created my `/usr/share/vim/vimfiles/doc/tags`, and installing quick-lint-js fails because it also creates that file.

**Comment by strager** [comment] 2021-12-10 10:23
Fixed in commit da0923bbb732d939148a1f44b630fe30026176d9. Installing `quick-lint-js-git` should now work. I will release a new version so that installing `quick-lint-js` works too.

**Comment by cahian** [comment] 2021-12-10 21:52
I confirm that `quick-lint-js-git` is working. :+1:

**Comment by strager** [comment] 2021-12-14 04:47
Shipped version 1.0.0 with the fix.

**Closed by strager** 2021-12-14 04:47 UTC
